plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'team.kuet_titanium.kuet_kinship'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "team.kuet_titanium.kuet_kinship"
        minSdk 31
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation 'io.github.muddz:styleabletoast:2.4.0'
    //implementation 'com.github.requery:sqlite-android:3.50.4'
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}